### ISSUE TITLE
Error while trying to docker compose up

### ISSUE THREAD

**Issue by mahbubhelal** [fhsinchy/guide-to-containerizing-laravel-applications#1]
This is the error I get while I try to start the container using docker compose.

**Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/local/bin/docker-php-entrypoint-dev": permission denied: unknown**

**Comment by fhsinchy** [comment]
@mdmahbubhelal are you using Windows or Linux?

**Comment by mahbubhelal** [comment]
Windows with wsl2.

**Comment by mahbubhelal** [comment]
I fixed the problem by adding the following lines to the Dockerfile
```
RUN chmod 755 /usr/local/bin/docker-php-entrypoint
RUN chmod 755 /usr/local/bin/docker-php-entrypoint-dev
```

Thanks for the awesome docker setup.
